# Generated by Django 4.1.3 on 2022-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
