# Generated by Django 4.1.3 on 2022-11-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpayuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="speedpayuser",
            name="name",
            field=models.CharField(default="oluwaseyi", max_length=50),
        ),
    ]
